---
- name: Install packages
  ansible.builtin.apt:
    install_recommends: false
    name: '{{ virt_packages }}'
    state: present

- name: Configure systemd
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    state: started

# Using macvtap/macvlan does not require forwarding on the host.
# - name: Configure sysctl
#   ansible.posix.sysctl:
#     name: net.ipv6.conf.all.forwarding
#     value: 1
#     state: present
#     sysctl_set: true

- name: Find base image
  ansible.builtin.stat:
    path: /var/lib/libvirt/images/{{ virt_base_image[ansible_architecture] }}
  register: _base_image

- name: Pull down image
  ansible.builtin.get_url:
    url: '{{ virt_base_image.url }}/{{ virt_base_image[ansible_architecture] }}'
    dest: /var/lib/libvirt/images/{{ virt_base_image[ansible_architecture] }}
    owner: root
    group: root
    mode: '0644'
  when: not _base_image.stat.exists
