---
- name: Manually remove netplan transient files and configs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ netplan_files }}"

- name: Remove netplan package
  ansible.builtin.apt:
    name: netplan.io
    state: absent

- name: Template out ethernet configuration
  ansible.builtin.template:
    src: 20-ethernet.network.j2
    dest: /etc/systemd/network/20-ethernet.network
    owner: root
    group: root
    mode: "0644"
  notify: Restart systemd-networkd

- name: Ensure resolve.conf points to systemd-resolved
  ansible.builtin.file:
    path: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Ensure services are enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - systemd-networkd
    - systemd-resolved

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
