---
- name: Check if VM exists already exists
  ansible.builtin.command: >
    virsh dominfo {{ inventory_hostname }}
  register: _dominfo
  failed_when: false

- name: Delete the VM
  ansible.builtin.include_tasks: delete.yaml
  when: '_dominfo.rc == 0'
