---
- name: Poweroff the VM
  ansible.builtin.command: >-
    virsh destroy {{ inventory_hostname }}
  failed_when: false
  changed_when: true

- name: Undefine the VM
  ansible.builtin.command: >-
    virsh undefine {{ inventory_hostname }} --nvram
  changed_when: true
  failed_when: false

- name: Delete the VM image directory
  ansible.builtin.file:
    path: /var/lib/libvirt/images/{{ inventory_hostname }}
    state: absent

# Supporting disk0 only at the moment because of... laziness.
- name: Delete the volume (RBD)
  when: virt_disks[0].pool == "ceph0" | default(false)
  ansible.builtin.command: >-
    rbd -c /etc/ceph/ceph.{{ virt_disks[0].pool }}.conf
      -k /etc/ceph/ceph.{{ virt_disks[0].pool }}.{{ libvirt_storage_pools.rbd[virt_disks[0].pool].ceph_auth_client_name }}.keyring
      --id {{ libvirt_storage_pools.rbd[virt_disks[0].pool].ceph_auth_client_name }}
      rm
      --pool {{ libvirt_storage_pools.rbd[virt_disks[0].pool].osd_pool }}
      --image {{ inventory_hostname }}-vda
#  ansible.builtin.command: >-
#    virsh vol-delete --pool ceph0 --vol {{ inventory_hostname }}-vda
  changed_when: true
