---
- name: Check if VM exists already exists
  ansible.builtin.command: >
    virsh list --name --all
  register: _virsh_list

- name: Delete the VM
  ansible.builtin.include_tasks: delete.yaml
  when: 'inventory_hostname in _virsh_list.stdout_lines'
