---
- name: Install packages
  ansible.builtin.apt:
    name: radvd
    state: present

- name: Template conf
  ansible.builtin.template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart radvd

- name: Systemd
  ansible.builtin.systemd:
    name: radvd
    state: started
    enabled: true
