---
- name: Create directory
  ansible.builtin.file:
    path: /opt/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Get files
  ansible.builtin.get_url:
    url: '{{ item.value.url }}'
    dest: /usr/local/bin/{{ item.key }}
    owner: root
    group: root
    mode: 0755
    checksum: 'sha256:{{ item.value.checksum }}'
  loop: '{{ kubernetes_binaries[ansible_architecture] | dict2items }}'
