---
- name: Ensure modules are loaded on boot
  ansible.builtin.template:
    src: k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure modules are currently loaded
  ansible.builtin.command: >
    modprobe {{ item }}
  changed_when: yes
  loop: '{{ kube_modules }}'

- name: Sysctl settings
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
  loop: '{{ kube_sysctl }}'

- name: Install first set of pre-req packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - containerd
    - curl
    - gpg

- name: Configure containerd
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644
  notify: restart containerd

- name: Start containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Add Kubernetes apt key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_short }}/deb/Release.key
    state: present

- name: Add Kubernetes repo
  ansible.builtin.apt_repository:
    repo: 'deb https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_short }}/deb/ /'
  register: _kube_repo_added

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: _kube_repo_added is changed

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop:
    - kubeadm
    - kubectl
    - kubelet

# Legacy code was here. Check out legacy.yaml.

- name: Start kubelet
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: started
