---
- name: Check if the network exists
  ansible.builtin.command: >-
    virsh net-info {{ _idx_network.key }}
  changed_when: false
  failed_when: false
  register: _net_info

- name: Create the network
  when: _net_info.rc != 0
  block:
    - name: Template the config
      ansible.builtin.template:
        src: "{{ _idx_network.value.type }}.xml.j2"
        dest: "{{ _temp.path }}/{{ _idx_network.key }}.xml"
        owner: root
        group: root
        mode: "0644"

    - name: Define the network
      ansible.builtin.command: >-
        virsh net-define {{ _temp.path }}/{{ _idx_network.key }}.xml
      changed_when: true

- name: Get the current network info
  ansible.builtin.command: >-
    virsh net-info {{ _idx_network.key }}
  changed_when: false
  register: _net_info

- name: Autostart the network
  when: _net_info.stdout_lines | select('match', '^Autostart:\\s*yes$') | list | length == 0
  ansible.builtin.command: >-
    virsh net-autostart --network {{ _idx_network.key }}
  changed_when: true

- name: Start the pool
  when: _net_info.stdout_lines | select('match', '^Active:\\s*yes$') | list | length == 0
  ansible.builtin.command: >-
    virsh net-start {{ _idx_network.key }}
  changed_when: true
