---
- name: Fetch facts
  ansible.builtin.setup:

- name: Ensure base image exists
  ansible.builtin.stat:
#    path: /var/lib/libvirt/images/{{ virt_base_image[hostvars[virt_host].ansible_architecture] }}
    path: /var/lib/libvirt/images/{{ virt_base_image["aarch64"] }}
  register: _stat_image

- name: Fail if image is missing
  ansible.builtin.fail:
    msg: Base image is missing
  when: not _stat_image.stat.exists

- name: Check if VM exists already exists
  ansible.builtin.command: >
    virsh list --name --all
  register: _virsh_list
  changed_when: false

- name: Create the VM
  ansible.builtin.include_tasks: create.yaml
  when: 'inventory_hostname not in _virsh_list.stdout_lines'

- name: Power on the VM
  ansible.builtin.command: >-
    virsh start {{ inventory_hostname }}
  changed_when: true
  failed_when: false    # This is a super lazy hack.
