---
- name: Ensure modules are loaded on boot
  ansible.builtin.template:
    src: k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure modules are currently loaded
  ansible.builtin.command: >
    modprobe {{ item }}
  changed_when: yes
  loop: '{{ kube_modules }}'

- name: Sysctl settings
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
  loop: '{{ kube_sysctl }}'

- name: Check to see if cri-tools exists
  ansible.builtin.stat:
    path: /opt/cri-tools/cri-tools.tar.gz
    checksum_algorithm: sha256
  register: _stat_cri_tools

- include_tasks: download_cri_tools.yaml
  when: (not _stat_cri_tools.stat.exists) or (_stat_cri_tools.stat.checksum != cri_tools[ansible_architecture].checksum)

- name: Check to see if correct kubeadm version exists
  ansible.builtin.stat:
    path: /usr/local/bin/kubeadm
    checksum_algorithm: sha256
  register: _stat_kubeadm

- include_tasks: download_kube_node.yaml
  when: (not _stat_kubeadm.stat.exists) or (_stat_kubeadm.stat.checksum != kubernetes_binaries[ansible_architecture].kubeadm.checksum)

- name: Copy kubelet systemd unit
  ansible.builtin.template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  notify: restart kubelet

- name: Systemd drop-in for kubelet
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart kubelet

- name: Copy kubelet drop-in unit
  ansible.builtin.template:
    src: 10-kubeadm.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart kubelet

- name: Start kubelet
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: started
